ALTER TABLE exchange_rate
MODIFY COLUMN rate DECIMAL(8,4) NOT NULL;

ALTER TABLE limits
MODIFY COLUMN limit_usd DECIMAL(8,4) NOT NULL DEFAULT 1000.0000;

ALTER TABLE limits
MODIFY COLUMN remains_before_exceed DECIMAL(8,2) NOT NULL DEFAULT 1000.00;


ALTER TABLE transactions
MODIFY COLUMN amount DECIMAL(8,4) NOT NULL;
