ALTER TABLE exchange_rate
MODIFY COLUMN rate DECIMAL(10,4) NOT NULL;

ALTER TABLE limits
MODIFY COLUMN limit_usd DECIMAL(10,4) NOT NULL DEFAULT 1000.0000;

ALTER TABLE limits
MODIFY COLUMN remains_before_exceed DECIMAL(10,4) NOT NULL DEFAULT 1000.00;


ALTER TABLE transactions
MODIFY COLUMN amount DECIMAL(10,4) NOT NULL;
